Repository fe9-4/taskify, pull requests merged in 2024-10, with the labels that each got.

#2 [Style] 테일윈드 커스텀 글자크기 및 색상 반영
  package.json
  public/icons/favicon.ico
  public/icons/visibility_off.svg
  public/icons/visibility_on.svg
  public/images/logo.png
  src/app/api/api.ts
  src/app/api/data.ts
  src/app/layout.tsx
  src/app/page.tsx
  src/hooks/useAuth.ts
  src/lib/api.ts
  src/lib/utils.ts
  src/styles/globals.css
  src/utils/helpers.ts
  tailwind.config.ts
Labels: 🎨 Style

#6 [Feat] Header 컴포넌트 및 회원가입/로그인 페이지 및 기능 및 보안관련 적용
  .github/ISSUE_TEMPLATE/build-template.md
  .github/ISSUE_TEMPLATE/chore-template.md
  .github/ISSUE_TEMPLATE/ci-template.md
  .github/ISSUE_TEMPLATE/delete-template.md
  .github/ISSUE_TEMPLATE/docs-template.md
  .github/ISSUE_TEMPLATE/feature-template.md
  .github/ISSUE_TEMPLATE/fix-template.md
  .github/ISSUE_TEMPLATE/refactor-template.md
  .github/ISSUE_TEMPLATE/style-template.md
  .github/ISSUE_TEMPLATE/test-template.md
  public/images/auth/logo.svg
  public/images/header/logo.svg
  public/images/header/logo_md.svg
  public/images/logo.png
  src/app/(auth)/layout.tsx
  src/app/(auth)/login/page.tsx
  src/app/(auth)/signup/page.tsx
  src/app/api/api.ts
  src/app/api/apiClient.ts
  src/app/api/auth/changePassword/route.ts
  src/app/api/auth/cookie/getCookie/route.ts
  src/app/api/auth/cookie/setCookie/route.ts
  src/app/api/auth/login/route.ts
  src/app/api/auth/logout/route.ts
  src/app/api/auth/signup/route.ts
  src/app/api/user/profile/route.ts
  src/app/layout.tsx
  src/components/Header.tsx
  src/constants/config.ts
  src/hooks/useAuth.ts
  src/store/userAtoms.ts
  src/zodSchema/authSchema.ts
  src/zodSchema/commonSchema.ts
  src/zodSchema/userSchema.ts
Labels: ✨ Feat

#13 [Feat] 드롭다운메뉴 및 칩 컴포넌트 추가
  public/images/cardImg1.png
  src/app/(home)/page.tsx
  src/app/dashboard/layout.tsx
  src/app/dashboard/page.tsx
  src/app/page.tsx
  src/components/Button.tsx
  src/components/chip/ColorChip.tsx
  src/components/chip/PlusAndNumChip.tsx
  src/components/chip/StatusChip.tsx
  src/components/chip/TagChip.tsx
  src/components/dashboard/ColumnItem.tsx
  src/components/dashboard/ColumnList.tsx
  src/components/dropdown/EditDeleteDropdown.tsx
  src/components/dropdown/SearchDropdown.tsx
  src/components/dropdown/StatusDropdown.tsx
  src/hooks/hooks.ts
  src/lib/utils.ts
  src/store/atoms.ts
  src/styles/globals.css
  src/styles/variables.css
  types/types.ts
Labels: ✨ Feat

#14 [Feat] 랜딩 페이지 구현
  public/images/landing/landing1.png
  public/images/landing/landing2.svg
  public/images/landing/landing3.svg
  public/images/landing/landing4.svg
  public/images/landing/landing5.svg
  public/images/landing/landing6.svg
  src/app/(home)/page.tsx
  src/app/layout.tsx
  src/components/home/Footer.tsx
  src/components/home/HeroSection.tsx
  src/components/home/MainSection.tsx
  src/components/home/SubSection.tsx
  src/styles/globals.css
  tailwind.config.ts
Labels: ✨ Feat

#16 [Feat] 버튼 컴포넌트 추가
  src/app/test/page.tsx
  src/components/ButtonComponents.tsx
  src/components/ButtonSetting.tsx
  src/lib/utils.ts
  tailwind.config.ts
Labels: ✨ Feat

#20 [Chore] Input 폴더 생성 및 Format 파일 수정
  src/components/input/InputDate.tsx
  src/components/input/InputFile.tsx
  src/components/input/InputItem.tsx
  src/types/formType.ts
  src/utils/dateFormat.ts
  src/utils/stringFormat.ts
Labels: 📦️ Chore

#23 [Refactor] 피드백 반영
  public/images/header/logo_home.svg
  public/images/header/logo_home_md.svg
  src/app/(auth)/layout.tsx
  src/app/(auth)/login/page.tsx
  src/app/(auth)/signup/page.tsx
  src/app/api/auth/changePassword/route.ts
  src/app/api/auth/cookie/getCookie/route.ts
  src/app/api/auth/cookie/setCookie/route.ts
  src/app/api/auth/login/route.ts
  src/app/api/auth/logout/route.ts
  src/app/api/auth/signup/route.ts
  src/app/api/user/profile/route.ts
  src/app/layout.tsx
  src/components/Header.tsx
  src/hooks/hooks.ts
  src/hooks/useAuth.ts
  src/hooks/useDebounce.ts
  src/hooks/useThrottle.ts
  src/zodSchema/authSchema.ts
  src/zodSchema/commonSchema.ts
  src/zodSchema/userSchema.ts
Labels: 🔨 Refactor

#29 [Refactor] 상태칩 prop 받는 형식으로 변경 및 상태드롭다운 코드 상태칩에 맞게 업데이트
  src/components/chip/StatusChip.tsx
  src/components/dropdown/StatusDropdown.tsx
Labels: 🔨 Refactor

#33 [Feat] 사이드바 추가
  package-lock.json
  src/app/(auth)/login/page.tsx
  src/app/(auth)/signup/page.tsx
  src/app/childrenLayout.tsx
  src/app/layout.tsx
  src/app/test/page.tsx
  src/components/Header.tsx
  src/components/button/ButtonComponents.tsx
  src/components/button/ButtonSetting.tsx
  src/components/input/InputItem.tsx
  src/components/sidebar/Button.tsx
  src/components/sidebar/DashboardItem.tsx
  src/components/sidebar/DashboardList.tsx
  src/components/sidebar/Logo.tsx
  src/components/sidebar/Sidebar.tsx
  src/hooks/useWidth.ts
  src/types/dashboardType.ts
Labels: ✨ Feat

#35 [Feat] 공용 모달 추가 및 대시보드 생성 모달 추가
  package.json
  src/app/layout.tsx
  src/app/test/page.tsx
  src/components/chip/SelectColorChip.tsx
  src/components/input/InputItem.tsx
  src/components/modal/CreateDashboard.tsx
  src/components/modal/ModalContainer.tsx
  src/components/modal/ModalContent.tsx
  src/store/modalAtom.ts
Labels: ✨ Feat

#37 [Feat] mypage 기본 기능만 추가, jotai userAtom 수정, apiClient 관련 수정 등
  package-lock.json
  src/app/(auth)/login/page.tsx
  src/app/api/apiClient.ts
  src/app/api/auth/changePassword/route.ts
  src/app/api/auth/login/route.ts
  src/app/api/auth/signup/route.ts
  src/app/api/user/profile/route.ts
  src/app/childrenLayout.tsx
  src/app/layout.tsx
  src/app/mypage/page.tsx
  src/components/Header.tsx
  src/components/input/InputItem.tsx
  src/components/modal/CreateDashboard.tsx
  src/constants/config.ts
  src/hooks/useAuth.ts
  src/store/userAtoms.ts
  src/types/formType.ts
  src/zodSchema/userSchema.ts
Labels: ✨ Feat

#38 [Feat] 할 일 생성 컴포넌트 추가
  src/app/api/cards/route.ts
  src/app/cards/layout.tsx
  src/app/cards/page.tsx
  src/components/cards/CreateCard.tsx
  src/components/chip/TagChip.tsx
  src/components/dropdown/SearchDropdown.tsx
  src/components/dropdown/StatusDropdown.tsx
  src/components/input/InputDate.tsx
  src/components/input/InputFile.tsx
  src/components/input/InputItem.tsx
  src/components/input/InputTag.tsx
  src/hooks/useInputFile.ts
  src/types/cardType.ts
  src/types/formType.ts
Labels: ✨ Feat

#46 [Feat] Alert 모달 추가
  src/app/layout.tsx
  src/app/test/page.tsx
  src/components/cards/CreateCard.tsx
  src/components/modal/AlertModal.tsx
  src/components/modal/CreateDashboard.tsx
  src/components/modal/ModalContainer.tsx
  src/store/atoms.ts
  src/store/modalAtom.ts
Labels: ✨ Feat

#47 [Feat] 내 대시보드 및 대시보드 페이지 구현
  public/images/myDashboard/invitation.svg
  src/app/api/dashboard/[dashboardId]/route.ts
  src/app/api/dashboard/columnList/route.ts
  src/app/api/myDashboard/invitation/route.ts
  src/app/api/myDashboard/route.ts
  src/app/dashboard/[dashboardId]/page.tsx
  src/app/dashboard/layout.tsx
  src/app/dashboard/page.tsx
  src/app/mydashboard/layout.tsx
  src/app/mydashboard/page.tsx
  src/components/button/ButtonComponents.tsx
  src/components/dashboard/ColumnItem.tsx
  src/components/dashboard/ColumnList.tsx
  src/components/myDashboard/Invitation.tsx
  src/components/myDashboard/Pagination.tsx
  src/types/dashboardType.ts
  src/types/myDashboardType.ts
  types/types.ts
Labels: ✨ Feat

#49 [Feat] 마이페이지 추가(프로필 수정, 비밀번호 변경 등) 및 useAuth 관련 리팩토링
  next.config.mjs
  package.json
  public/icons/previous_arrow.svg
  src/app/(auth)/login/page.tsx
  src/app/(auth)/signup/page.tsx
  src/app/api/auth/changePassword/route.ts
  src/app/api/auth/login/route.ts
  src/app/api/user/profile/image/route.ts
  src/app/api/user/profile/route.ts
  src/app/childrenLayout.tsx
  src/app/dashboard/layout.tsx
  src/app/layout.tsx
  src/app/mypage/components/ChangePassword.tsx
  src/app/mypage/components/UpdateProfile.tsx
  src/app/mypage/page.tsx
  src/components/Header.tsx
  src/components/button/ButtonComponents.tsx
  src/components/cards/CreateCard.tsx
  src/components/dropdown/SearchDropdown.tsx
  src/components/input/InputItem.tsx
  src/hooks/useAuth.ts
  src/hooks/useFileUpload.ts
  src/zodSchema/authSchema.ts
  src/zodSchema/userSchema.ts
Labels: ✨ Feat

#53 [Feat] 할 일 수정 컴포넌트 추가
  src/app/api/cards/route.ts
  src/app/cards/page.tsx
  src/components/cards/UpdateCard.tsx
Labels: ✨ Feat

#58 [Feat] 초대목록 구현 및 실제데이터에 페이지네이션, 무한스크롤 적용
  src/app/api/dashboard/columnList/route.ts
  src/app/api/myDashboard/invitation/[invitationId]/route.ts
  src/app/api/myDashboard/route.ts
  src/app/dashboard/[dashboardId]/page.tsx
  src/app/dashboard/components/ColumnItem.tsx
  src/app/dashboard/components/ColumnList.tsx
  src/app/mydashboard/components/Invitation.tsx
  src/app/mydashboard/components/InviteList.tsx
  src/app/mydashboard/components/Pagination.tsx
  src/app/mydashboard/page.tsx
  src/components/myDashboard/Invitation.tsx
  src/components/sidebar/DashboardItem.tsx
  src/store/myDashboardAtom.ts
  src/types/myDashboardType.ts
Labels: ✨ Feat

#66 [Feat] useDashboardMember 훅 및 Header 대시보드와 구성원들 관련 및 버그 수정
  package.json
  src/app/(auth)/login/page.tsx
  src/app/(auth)/signup/page.tsx
  src/app/api/auth/login/route.ts
  src/app/api/members/[memberId]/route.ts
  src/app/api/members/route.ts
  src/app/api/users/me/image/route.ts
  src/app/api/users/me/route.ts
  src/app/api/users/route.ts
  src/app/layout.tsx
  src/app/mydashboard/components/Pagination.tsx
  src/app/mypage/components/UpdateProfile.tsx
  src/app/mypage/page.tsx
  src/components/Header.tsx
  src/components/cards/UpdateCard.tsx
  src/components/header/Header.tsx
  src/components/header/Logo.tsx
  src/components/header/UserMenu.tsx
  src/components/header/dashboard/DashboardMemberDisplay.tsx
  src/components/header/dashboard/MemberInitials.tsx
  src/components/header/dashboard/SelectedDashboard.tsx
  src/components/input/InputTag.tsx
  src/hooks/useAuth.ts
  src/hooks/useDashboardList.ts
  src/hooks/useDashboardMember.ts
  src/zodSchema/commonSchema.ts
  src/zodSchema/dashboardSchema.ts
  src/zodSchema/memberSchema.ts
Labels: ✨ Feat

#61 [Feat] 대시보드 생성 모달 api 연결
  src/app/api/dashboards/route.ts
  src/components/button/ButtonComponents.tsx
  src/components/chip/SelectColorChip.tsx
  src/components/modal/CreateDashboard.tsx
  src/hooks/useLoading.ts
  src/types/dashboardType.ts
Labels: ✨ Feat

#62 [Refactor] 할 일 생성 카드 react-hook-form 개선 및 api 연결
  src/app/api/cards/[cardId]/route.ts
  src/app/api/cards/route.ts
  src/app/api/columns/[columnId]/card-image/route.ts
  src/app/cards/[cardId]/page.tsx
  src/app/cards/layout.tsx
  src/app/cards/page.tsx
  src/app/dashboard/[dashboardId]/page.tsx
  src/app/mydashboard/components/Pagination.tsx
  src/components/button/ButtonComponents.tsx
  src/components/cards/CreateCard.tsx
  src/components/cards/UpdateCard.tsx
  src/components/dropdown/SearchDropdown.tsx
  src/components/dropdown/StatusDropdown.tsx
  src/components/input/InputDate.tsx
  src/components/input/InputFile.tsx
  src/components/input/InputItem.tsx
  src/components/input/InputTag.tsx
  src/types/formType.ts
  src/utils/dateFormat.ts
Labels: 🔨 Refactor

#70 [Feat] edit 페이지 추가
  package.json
  src/app/api/dashboard/[dashboardId]/route.ts
  src/app/api/dashboard/list/route.ts
  src/app/api/dashboards/[dashboardId]/invitations/route.ts
  src/app/api/dashboards/[dashboardId]/route.ts
  src/app/api/dashboards/columnList/route.ts
  src/app/api/dashboards/route.ts
  src/app/dashboard/[dashboardId]/edit/components/DashboardMemberItem.tsx
  src/app/dashboard/[dashboardId]/edit/components/DashboardMemberList.tsx
  src/app/dashboard/[dashboardId]/edit/components/EditDashboard.tsx
  src/app/dashboard/[dashboardId]/edit/components/SectionTitle.tsx
  src/app/dashboard/[dashboardId]/edit/page.tsx
  src/app/test/page.tsx
  src/components/button/ButtonComponents.tsx
  src/components/sidebar/DashboardItem.tsx
  src/components/sidebar/Sidebar.tsx
  src/types/invitationType.ts
  tsconfig.json
Labels: ✨ Feat

#71 [Refactor] api 폴더구조 변경 등
  src/app/api/cards/route.ts
  src/app/api/columns/route.ts
  src/app/api/dashboards/list/route.ts
  src/app/api/dashboards/route.ts
  src/app/api/invitations/[invitationId]/route.ts
  src/app/api/invitations/route.ts
  src/app/api/myDashboard/route.ts
  src/app/dashboard/[dashboardId]/page.tsx
  src/app/dashboard/components/ColumnItem.tsx
  src/app/dashboard/components/ColumnList.tsx
  src/app/loading.tsx
  src/app/mydashboard/components/Invitation.tsx
  src/app/mydashboard/components/InviteItem.tsx
  src/app/mydashboard/components/InviteList.tsx
  src/app/mydashboard/components/Pagination.tsx
  src/app/mydashboard/layout.tsx
  src/app/mydashboard/page.tsx
  src/components/dropdown/SearchDropdown.tsx
  src/components/dropdown/StatusDropdown.tsx
  src/types/myDashboardType.ts
Labels: 🔨 Refactor

#85 [Fix] 내 대시보드, 대시보드 페이지 목록 요청 버그 수정, 자잘한 사항 수정
  src/app/api/cards/route.ts
  src/app/api/dashboards/columnList/route.ts
  src/app/api/dashboards/route.ts
  src/app/api/invitations/route.ts
  src/app/dashboard/components/ColumnItem.tsx
  src/app/dashboard/components/ColumnList.tsx
  src/app/mydashboard/components/InviteList.tsx
  src/app/mydashboard/components/Pagination.tsx
  src/types/dashboardType.ts
  src/types/myDashboardType.ts
Labels: 🐞 Fix

#87 [Feat] 컬럼 생성 모달 및 대시보드 초대 모달 추가
  src/app/(home)/components/HeroSection.tsx
  src/app/api/columns/route.ts
  src/app/api/dashboards/[dashboardId]/invitations/route.ts
  src/app/dashboard/[dashboardId]/edit/components/SectionTitle.tsx
  src/app/dashboard/[dashboardId]/page.tsx
  src/app/test/page.tsx
  src/components/button/ButtonComponents.tsx
  src/components/modal/CreateColumn.tsx
  src/components/modal/CreateDashboard.tsx
  src/components/modal/InvitationDashboard.tsx
  src/components/modal/ModalContainer.tsx
  src/store/modalAtom.ts
Labels: ✨ Feat

#88 [Feat] edit 페이지 - 중간 공유
  src/app/api/dashboards/[dashboardId]/invitations/[invitationsId]/route.ts
  src/app/api/dashboards/[dashboardId]/invitations/route.ts
  src/app/api/dashboards/[dashboardId]/route.ts
  src/app/dashboard/[dashboardId]/edit/components/DashboardMemberItem.tsx
  src/app/dashboard/[dashboardId]/edit/components/DashboardMemberList.tsx
  src/app/dashboard/[dashboardId]/edit/components/EditDashboard.tsx
  src/app/dashboard/[dashboardId]/edit/components/InviteList.tsx
  src/app/dashboard/[dashboardId]/edit/components/MemberItem.tsx
  src/app/dashboard/[dashboardId]/edit/components/Section.tsx
  src/app/dashboard/[dashboardId]/edit/components/SectionTitle.tsx
  src/app/dashboard/[dashboardId]/edit/page.tsx
  src/app/dashboard/components/ColumnItem.tsx
  src/app/dashboard/components/ColumnList.tsx
  src/components/cards/CreateCard.tsx
  src/components/sidebar/Button.tsx
  src/components/sidebar/DashboardItem.tsx
  src/components/sidebar/DashboardList.tsx
  src/components/sidebar/Sidebar.tsx
  src/types/dashboardType.ts
Labels: ✨ Feat

#96 [Feat] 할 일 카드 상세 조회 추가
  public/icons/cancel_icon.svg
  public/icons/kebab_icon.svg
  src/app/api/cards/[cardId]/route.ts
  src/app/api/cards/route.ts
  src/app/cards/[cardId]/page.tsx
  src/app/cards/layout.tsx
  src/app/cards/page.tsx
  src/app/dashboard/components/ColumnItem.tsx
  src/app/dashboard/components/ColumnList.tsx
  src/components/button/ButtonComponents.tsx
  src/components/cards/CreateCard.tsx
  src/components/cards/UpdateCard.tsx
  src/components/dropdown/SearchDropdown.tsx
  src/components/dropdown/StatusDropdown.tsx
  src/components/input/InputDate.tsx
  src/components/input/InputFile.tsx
  src/components/input/InputItem.tsx
  src/components/input/InputTag.tsx
  src/components/modal/AlertModal.tsx
  src/components/modal/ModalContainer.tsx
  src/components/modal/cards/DetailCard.tsx
  src/store/modalAtom.ts
  src/types/cardType.ts
  src/types/formType.ts
  src/zodSchema/cardSchema.ts
Labels: ✨ Feat

#91 [Feat] Header 관리 및 초대하기 추가, 이미지 업로드 관련 컴포넌트 제외하고 원복
  next.config.mjs
  public/images/header/invitation.svg
  public/images/header/setting.svg
  public/images/loading/logo.svg
  src/app/api/auth/checkCookie/route.ts
  src/app/api/auth/login/route.ts
  src/app/api/cards/[cardId]/route.ts
  src/app/childrenLayout.tsx
  src/app/loading.tsx
  src/app/mypage/components/UpdateProfile.tsx
  src/app/mypage/page.tsx
  src/app/test/page.tsx
  src/components/dropdown/SearchDropdown.tsx
  src/components/header/Header.tsx
  src/components/header/Logo.tsx
  src/components/header/UserMenu.tsx
  src/components/header/dashboard/DashboardMemberDisplay.tsx
  src/components/header/dashboard/MemberInitials.tsx
  src/components/header/dashboard/SelectedDashboard.tsx
  src/components/modal/InvitationDashboard.tsx
  src/components/modal/cards/CreateCard.tsx
  src/components/modal/cards/UpdateCard.tsx
  src/hooks/useAuth.ts
  src/hooks/useDashboardList.ts
  src/hooks/useDashboardMember.ts
  src/hooks/useFileUpload.ts
  src/hooks/useInvitation.ts
  src/store/loadingAtom.ts
  src/types/cardType.ts
  src/types/currentManager.ts
  src/types/dashboardType.ts
  src/types/uploadType.ts
  src/zodSchema/cardSchema.ts
  src/zodSchema/invitationSchema.ts
Labels: ✨ Feat

#100 [Feat] 에러바운더리 설정, 내 대시보드 초대목록 중복 노출 제거
  public/icons/error.png
  public/icons/notFound.png
  src/app/api/invitations/[invitationId]/route.ts
  src/app/dashboard/[dashboardId]/error.tsx
  src/app/dashboard/[dashboardId]/page.tsx
  src/app/dashboard/components/ColumnItem.tsx
  src/app/dashboard/components/ColumnList.tsx
  src/app/global-error.tsx
  src/app/mydashboard/components/InviteList.tsx
  src/app/mydashboard/error.tsx
  src/app/mydashboard/page.tsx
  src/app/not-found.tsx
  src/components/button/ButtonComponents.tsx
  src/components/pagination/Pagination.tsx
  src/types/myDashboardType.ts
Labels: ✨ Feat

#108 [Feat] edit 페이지 - 기능 추가 및 개선
  src/app/api/dashboards/[dashboardId]/invitations/[invitationId]/route.ts
  src/app/api/dashboards/[dashboardId]/invitations/route.ts
  src/app/api/dashboards/[dashboardId]/route.ts
  src/app/api/members/[memberId]/route.ts
  src/app/dashboard/[dashboardId]/edit/components/DashboardMemberList.tsx
  src/app/dashboard/[dashboardId]/edit/components/EditDashboard.tsx
  src/app/dashboard/[dashboardId]/edit/components/InviteItem.tsx
  src/app/dashboard/[dashboardId]/edit/components/InviteList.tsx
  src/app/dashboard/[dashboardId]/edit/components/MemberItem.tsx
  src/app/dashboard/[dashboardId]/edit/page.tsx
  src/app/dashboard/components/ColumnList.tsx
Labels: ✨ Feat

#111 [Feat] 대시보드 삭제 기능 추가
  src/app/api/columns/[columnId]/route.ts
  src/app/api/dashboards/[dashboardId]/route.ts
  src/app/dashboard/[dashboardId]/edit/page.tsx
  src/components/button/ButtonComponents.tsx
Labels: ✨ Feat

#114 [Feat] 대시보드 카드 업로드하면 실시간 반영, 초대목록 중복방지 로직 보완, 메타데이터 보완
  src/app/dashboard/[dashboardId]/page.tsx
  src/app/dashboard/components/ColumnList.tsx
  src/app/dashboard/layout.tsx
  src/app/layout.tsx
  src/app/mydashboard/components/InviteItem.tsx
  src/app/mydashboard/layout.tsx
  src/app/mydashboard/page.tsx
  src/components/dropdown/SearchDropdown.tsx
  src/components/modal/cards/CreateCard.tsx
  src/components/modal/cards/DetailCard.tsx
  src/store/dashboardAtom.ts
  src/store/myDashboardAtom.ts
Labels: ✨ Feat

#119 [Feat] 댓글 생성, 조회, 수정 삭제 기능 추가
  src/app/api/comments/[commentId]/route.ts
  src/app/api/comments/route.ts
  src/app/dashboard/components/ColumnList.tsx
  src/components/dropdown/EditDeleteDropdown.tsx
  src/components/input/InputItem.tsx
  src/components/modal/cards/DetailCard.tsx
  src/components/modal/comments/CommentList.tsx
  src/components/modal/comments/CreateComment.tsx
  src/store/modalAtom.ts
  src/store/myDashboardAtom.ts
  src/types/commentType.ts
  src/types/formType.ts
  src/utils/dateFormat.ts
Labels: ✨ Feat

#121 [Chore] edit 페이지 - 반응형 추가 및 기타 수정
  src/app/api/invitations/[invitationId]/route.ts
  src/app/api/members/[memberId]/route.ts
  src/app/dashboard/[dashboardId]/edit/components/DashboardMemberList.tsx
  src/app/dashboard/[dashboardId]/edit/components/InviteList.tsx
  src/app/dashboard/[dashboardId]/edit/components/MemberItem.tsx
  src/app/dashboard/[dashboardId]/edit/layout.tsx
  src/app/dashboard/[dashboardId]/edit/page.tsx
  src/components/pagination/Pagination.tsx
  src/components/sidebar/Sidebar.tsx
Labels: 📦️ Chore

#122 [Chore] 일부 수정사항 공유
  src/app/dashboard/[dashboardId]/edit/components/DashboardMemberList.tsx
  src/app/dashboard/[dashboardId]/edit/components/InviteList.tsx
  src/app/dashboard/components/ColumnList.tsx
  src/components/button/ButtonComponents.tsx
  src/components/pagination/Pagination.tsx
  src/components/sidebar/Button.tsx
  src/components/sidebar/DashboardItem.tsx
  src/components/sidebar/DashboardList.tsx
  src/components/sidebar/Logo.tsx
  src/components/sidebar/Sidebar.tsx
  src/hooks/useMember.ts
Labels: 📦️ Chore

#125 [Feat] 모달 상태 관리 최적화
  src/app/(home)/components/HeroSection.tsx
  src/app/dashboard/[dashboardId]/edit/components/InviteList.tsx
  src/app/dashboard/[dashboardId]/edit/page.tsx
  src/app/dashboard/[dashboardId]/page.tsx
  src/app/dashboard/components/ColumnList.tsx
  src/app/mydashboard/page.tsx
  src/components/header/dashboard/DashboardMemberDisplay.tsx
  src/components/modal/DeleteModal.tsx
  src/components/modal/ModalContainer.tsx
  src/components/modal/ModalContent.tsx
  src/components/modal/cards/CreateCard.tsx
  src/components/modal/cards/DetailCard.tsx
  src/components/modal/cards/UpdateCard.tsx
  src/components/modal/columns/CreateColumn.tsx
  src/components/modal/columns/EditColumn.tsx
  src/components/modal/comments/CommentList.tsx
  src/components/modal/dashboard/CreateDashboard.tsx
  src/components/modal/dashboard/InvitationDashboard.tsx
  src/components/sidebar/Button.tsx
  src/hooks/useToggleModal.ts
  src/store/modalAtom.ts
Labels: ✨ Feat

#129 [Feat] 댓글 무한스크롤 기능 추가 및 댓글 생성 실시간 반영
  src/app/api/comments/route.ts
  src/components/button/ButtonComponents.tsx
  src/components/dropdown/SearchDropdown.tsx
  src/components/input/InputItem.tsx
  src/components/modal/cards/CreateCard.tsx
  src/components/modal/cards/DetailCard.tsx
  src/components/modal/comments/CommentItem.tsx
  src/components/modal/comments/CommentList.tsx
  src/components/modal/comments/CreateComment.tsx
  src/components/sidebar/Button.tsx
  src/hooks/useObserver.ts
  src/types/commentType.ts
  src/types/formType.ts
Labels: ✨ Feat

#130 [Fix] 상태 및 검색드롭다운 수정, 실시간 반영 보완, 404페이지 수정
  public/icons/notFound.png
  src/app/api/invitations/[invitationId]/route.ts
  src/app/dashboard/[dashboardId]/page.tsx
  src/app/dashboard/components/ColumnItem.tsx
  src/app/dashboard/components/ColumnList.tsx
  src/app/not-found.tsx
  src/components/dropdown/SearchDropdown.tsx
  src/components/dropdown/StatusDropdown.tsx
  src/components/modal/cards/DetailCard.tsx
  src/components/modal/cards/UpdateCard.tsx
  src/store/dashboardAtom.ts
  src/types/dashboardType.ts
Labels: 🐞 Fix

#132 [Chore] InviteItem 에서 dashboardId 는 필요하지 않으므로 제거 및 자잘한 수정
  src/app/mydashboard/components/InviteItem.tsx
  src/components/header/UserMenu.tsx
  src/hooks/useInvitation.ts
Labels: 📦️ Chore

#134 [Build] develop 브랜치 배포 오류 수정
  src/app/mydashboard/components/InviteItem.tsx
  src/components/input/InputItem.tsx
  src/components/modal/cards/DetailCard.tsx
  src/components/modal/comments/CommentList.tsx
  src/hooks/useObserver.ts
  src/hooks/useWidth.ts
Labels: ⚙ Build

#136 [Fix] 관리 페이지 - 멤버 삭제 업데이트 수정
  src/app/dashboard/[dashboardId]/edit/layout.tsx
  src/app/dashboard/[dashboardId]/edit/page.tsx
  src/app/dashboard/layout.tsx
  src/app/layout.tsx
  src/components/modal/cards/DetailCard.tsx
  src/hooks/useMember.ts
Labels: 🐞 Fix

#138 [Feat] delete 모달 상태 관리 최적화
  src/app/dashboard/[dashboardId]/edit/components/InviteList.tsx
  src/app/dashboard/[dashboardId]/edit/page.tsx
  src/app/dashboard/[dashboardId]/page.tsx
  src/app/dashboard/components/ColumnList.tsx
  src/app/mydashboard/page.tsx
  src/components/header/dashboard/DashboardMemberDisplay.tsx
  src/components/modal/DeleteModal.tsx
  src/components/modal/ModalContainer.tsx
  src/components/modal/cards/CreateCard.tsx
  src/components/modal/cards/DetailCard.tsx
  src/components/modal/cards/UpdateCard.tsx
  src/components/modal/columns/CreateColumn.tsx
  src/components/modal/columns/EditColumn.tsx
  src/components/modal/dashboard/CreateDashboard.tsx
  src/components/modal/dashboard/InvitationDashboard.tsx
  src/components/sidebar/Button.tsx
  src/hooks/useModal.ts
  src/hooks/useToggleModal.ts
  src/store/modalAtom.ts
Labels: ✨ Feat
