Repository fe9-4/taskify, pull requests merged in 2024-11, with the labels that each got.

#144 [Fix] 대시보드 무한스크롤 수정
  src/app/api/cards/route.ts
  src/app/dashboard/[dashboardId]/page.tsx
  src/app/dashboard/components/ColumnList.tsx
  src/app/layout.tsx
  src/components/dropdown/StatusDropdown.tsx
  src/components/modal/cards/UpdateCard.tsx
  src/components/modal/comments/CommentList.tsx
  src/hooks/useObserver.ts
  src/types/dashboardType.ts
Labels: 🐞 Fix

#143 [Fix] 무한 스크롤 무한 루프 및 배포 오류 수정
  src/app/dashboard/components/ColumnList.tsx
  src/components/chip/TagChip.tsx
  src/components/dropdown/SearchDropdown.tsx
  src/components/dropdown/StatusDropdown.tsx
  src/components/input/InputDate.tsx
  src/components/input/InputItem.tsx
  src/components/input/InputTag.tsx
  src/components/modal/cards/CreateCard.tsx
  src/components/modal/cards/DetailCard.tsx
  src/components/modal/cards/UpdateCard.tsx
  src/components/modal/comments/CommentItem.tsx
  src/components/modal/comments/CommentList.tsx
  src/hooks/useObserver.ts
  src/store/modalAtom.ts
  src/types/cardType.ts
  src/types/formType.ts
  src/zodSchema/cardSchema.ts
Labels: 🐞 Fix

#140 [Feat] 대시보드 카드 드래그 앤 드랍 추가
  package.json
  src/app/(auth)/layout.tsx
  src/app/childrenLayout.tsx
  src/app/dashboard/[dashboardId]/edit/components/EditDashboard.tsx
  src/app/dashboard/[dashboardId]/page.tsx
  src/app/dashboard/components/ColumnItem.tsx
  src/app/dashboard/components/ColumnList.tsx
  src/app/mydashboard/page.tsx
  src/components/header/Header.tsx
  src/components/header/dashboard/DashboardMemberDisplay.tsx
  src/components/header/dashboard/SelectedDashboard.tsx
  src/components/modal/dashboard/InvitationDashboard.tsx
  src/components/sidebar/Sidebar.tsx
  src/hooks/useAuth.ts
  src/hooks/useCard.ts
  src/hooks/useColumn.ts
  src/hooks/useDashboard.ts
  src/store/dashboardAtom.ts
  src/store/userAtoms.ts
  src/zodSchema/cardSchema.ts
  src/zodSchema/columnSchema.ts
  src/zodSchema/commonSchema.ts
  src/zodSchema/dashboardSchema.ts
Labels: ✨ Feat

#152 [Chore] atom setter 함수 호출 수정, 대시보드 생성 페이지 이동 오류 수정
  src/app/dashboard/[dashboardId]/page.tsx
  src/app/dashboard/components/ColumnList.tsx
  src/app/mydashboard/components/InviteItem.tsx
  src/app/mydashboard/page.tsx
  src/components/header/Header.tsx
  src/components/header/dashboard/DashboardMemberDisplay.tsx
  src/components/modal/cards/CreateCard.tsx
  src/components/modal/cards/DetailCard.tsx
  src/components/modal/cards/UpdateCard.tsx
  src/components/modal/columns/CreateColumn.tsx
  src/components/modal/columns/EditColumn.tsx
  src/components/modal/dashboard/CreateDashboard.tsx
  src/store/modalAtom.ts
Labels: 📦️ Chore

#154 [Chore] 태그 글자 수 제한, 할 일 상세 조회 텍스트 수정, 상단 이동 버튼 추가 등
  src/components/input/InputDate.tsx
  src/components/input/InputItem.tsx
  src/components/input/InputTag.tsx
  src/components/modal/cards/CreateCard.tsx
  src/components/modal/cards/DetailCard.tsx
  src/components/modal/cards/UpdateCard.tsx
  src/components/modal/comments/CommentItem.tsx
  src/components/modal/comments/CommentList.tsx
  src/components/modal/comments/CreateComment.tsx
  src/styles/globals.css
  src/types/commentType.ts
Labels: 📦️ Chore

#153 [Refactor] 대시보드 CRUD 를 useDashboard 훅으로 관리
  src/app/(auth)/layout.tsx
  src/app/api/dashboards/[dashboardId]/route.ts
  src/app/api/dashboards/route.ts
  src/app/api/invitations/route.ts
  src/app/dashboard/[dashboardId]/edit/components/EditDashboard.tsx
  src/app/dashboard/[dashboardId]/edit/page.tsx
  src/app/dashboard/[dashboardId]/page.tsx
  src/app/dashboard/components/ColumnItem.tsx
  src/app/dashboard/components/ColumnList.tsx
  src/app/layout.tsx
  src/app/mydashboard/components/InviteList.tsx
  src/components/chip/SelectColorChip.tsx
  src/components/header/dashboard/DashboardMemberDisplay.tsx
  src/components/modal/dashboard/CreateDashboard.tsx
  src/components/modal/dashboard/InvitationDashboard.tsx
  src/components/sidebar/Sidebar.tsx
  src/hooks/useDashboard.ts
  src/hooks/useInvitation.ts
  src/types/dashboardType.ts
  src/zodSchema/dashboardSchema.ts
Labels: 🔨 Refactor

#156 [Refactor] 대시보드 무한 스크롤, 버튼 더 보기
  src/app/dashboard/[dashboardId]/page.tsx
  src/app/dashboard/components/ColumnList.tsx
Labels: 🔨 Refactor

#159 [Chore] 토스트 메세지 관리
  src/app/(auth)/login/page.tsx
  src/app/(auth)/signup/page.tsx
  src/app/dashboard/[dashboardId]/edit/components/InviteList.tsx
  src/app/dashboard/[dashboardId]/edit/components/MemberItem.tsx
  src/app/dashboard/[dashboardId]/edit/page.tsx
  src/app/dashboard/[dashboardId]/page.tsx
  src/app/dashboard/components/ColumnList.tsx
  src/app/mydashboard/components/InviteItem.tsx
  src/app/mypage/components/ChangePassword.tsx
  src/app/mypage/components/UpdateProfile.tsx
  src/components/modal/cards/CreateCard.tsx
  src/components/modal/cards/DetailCard.tsx
  src/components/modal/cards/UpdateCard.tsx
  src/components/modal/columns/CreateColumn.tsx
  src/components/modal/columns/EditColumn.tsx
  src/components/modal/comments/CommentItem.tsx
  src/components/modal/comments/CommentList.tsx
  src/components/modal/comments/CreateComment.tsx
  src/components/modal/dashboard/CreateDashboard.tsx
  src/components/modal/dashboard/InvitationDashboard.tsx
  src/components/pagination/Pagination.tsx
  src/hooks/useCard.ts
  src/hooks/useColumn.ts
  src/hooks/useDashboard.ts
  src/hooks/useInvitation.ts
  src/hooks/useMember.ts
  src/lib/toastMessage.ts
Labels: 📦️ Chore

#158 [Fix] 대시보드 무한스크롤 버그 수정, 내 대시보드 버그 수정 등
  src/app/dashboard/[dashboardId]/page.tsx
  src/app/dashboard/components/ColumnItem.tsx
  src/app/dashboard/components/ColumnList.tsx
  src/app/mydashboard/components/InviteList.tsx
Labels: 🐞 Fix

#167 [Fix] 존재하던 버그 수정 및 스타일 수정 (원님 PR + 혜민님 PR 결합)
  src/app/(auth)/layout.tsx
  src/app/(auth)/login/error.tsx
  src/app/(auth)/signup/error.tsx
  src/app/api/cards/[cardId]/route.ts
  src/app/dashboard/[dashboardId]/edit/components/DashboardMemberList.tsx
  src/app/dashboard/[dashboardId]/edit/error.tsx
  src/app/dashboard/[dashboardId]/edit/page.tsx
  src/app/dashboard/[dashboardId]/page.tsx
  src/app/dashboard/components/ColumnItem.tsx
  src/app/dashboard/components/ColumnList.tsx
  src/app/dashboard/layout.tsx
  src/app/layout.tsx
  src/app/mydashboard/components/InviteList.tsx
  src/app/mydashboard/page.tsx
  src/app/mypage/error.tsx
  src/app/mypage/layout.tsx
  src/app/mypage/page.tsx
  src/components/dropdown/SearchDropdown.tsx
  src/components/dropdown/StatusDropdown.tsx
  src/components/header/dashboard/DashboardMemberDisplay.tsx
  src/components/header/dashboard/MemberInitials.tsx
  src/components/modal/cards/CreateCard.tsx
  src/components/modal/cards/DetailCard.tsx
  src/components/modal/cards/UpdateCard.tsx
  src/components/modal/dashboard/InvitationDashboard.tsx
  src/components/sidebar/Sidebar.tsx
  src/hooks/useDashboard.ts
  src/hooks/useInvitation.ts
  src/hooks/useMember.ts
  src/lib/toastMessage.ts
  src/store/dashboardAtom.ts
  src/styles/globals.css
Labels: 🐞 Fix

#170 [Style] dashboard CSS 변경
  src/app/dashboard/[dashboardId]/page.tsx
  src/app/dashboard/components/ColumnList.tsx
  src/app/dashboard/layout.tsx
  src/app/mydashboard/layout.tsx
  src/components/dropdown/SearchDropdown.tsx
  src/components/dropdown/StatusDropdown.tsx
  src/components/modal/cards/UpdateCard.tsx
  src/styles/globals.css
Labels: 🎨 Style

#172 [Chore] 자잘한 오류 수정
  src/app/(home)/components/Footer.tsx
  src/app/dashboard/[dashboardId]/page.tsx
  src/app/layout.tsx
Labels: 📦️ Chore

#176 [Fix] 드롭다운 z-index수정
  src/components/dropdown/StatusDropdown.tsx
Labels: 📦️ Chore, 🐞 Fix

#179 [Fix] 로그인 후 dashboard 및 invitation 목록 API가 무한 호출 되는 문제
  src/app/dashboard/[dashboardId]/edit/components/DashboardMemberList.tsx
  src/app/dashboard/[dashboardId]/page.tsx
  src/app/dashboard/components/ColumnList.tsx
  src/app/mydashboard/components/InviteList.tsx
  src/app/mydashboard/page.tsx
  src/components/dropdown/StatusDropdown.tsx
  src/components/modal/cards/UpdateCard.tsx
  src/components/modal/dashboard/InvitationDashboard.tsx
  src/components/sidebar/Sidebar.tsx
  src/hooks/useDashboard.ts
  src/hooks/useInvitation.ts
  src/lib/toastMessage.ts
  src/store/dashboardAtom.ts
Labels: 🐞 Fix

#182 [Fix] 미들웨어로 cookie 체크를 해서 무한 로딩 대응
  README.md
  src/app/childrenLayout.tsx
  src/hooks/useAuth.ts
  src/middleware.ts
Labels: 🐞 Fix
